# Generated by Django 5.2.3 on 2025-07-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_remove_comment_user_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateField(verbose_name="Commented on"),
        ),
    ]
