# Generated by Django 5.2.3 on 2025-07-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Commented on'),
        ),
    ]
