# Generated by Django 5.2.3 on 2025-07-15 21:01

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=main_app.models.PhotoImageStorage(), upload_to='postsphotos/'),
        ),
    ]
