# Generated by Django 5.2.3 on 2025-07-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_post_image'),
        ('main_app', '0010_post_country'),
    ]

    operations = [
    ]
