# Generated by Django 5.2.3 on 2025-07-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0012_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
