# Generated by Django 5.2.3 on 2025-07-16 04:48

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_post_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=main_app.models.PhotoImageStorage(), upload_to='postsphotos/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
