# Generated by Django 5.2.3 on 2025-07-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0013_alter_post_tags"),
        ("main_app", "0015_remove_post_tags_post_tags"),
    ]

    operations = []
